---
- hosts: a1_update_compose
  become: true
  roles:
    - composeupgrade

- hosts: a1_update_portainer_agent
  become: true
  roles:
    - portaineragentupgrade

- hosts: a1_update_portainer
  become: true
  roles:
    - portainerupgrade

- hosts: a1_update_omv
  become: true
  roles:
    - omvupgrade

- hosts: a1_update_apt
  become: true
  roles:
    - aptupgrade
