---
- hosts: dns_repair
  become: true
  roles:
    - dns_repair

- hosts: update_compose
  become: true
  roles:
    - composeupgrade_a1

- hosts: update_portainer_agent
  become: true
  roles:
    - portaineragentupgrade

- hosts: update_portainer
  become: true
  roles:
    - portainerupgrade

- hosts: update_omv
  become: true
  roles:
    - omvupgrade

- hosts: update_apt
  become: true
  roles:
    - aptupgrade
