- name: Add Zabbix repository
  tags: dpkg, zabbix, apt, agent2
  apt_repository:
    repo: deb https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb
    state: present
