# Portainerupgrade variables
portainer_name: portainer2
portainer_image_name: portainer/portainer-ce:sts

# Portaineragentupgrade variables
portainer_agent_name: portainer_agent_backup
portainer_agent_image_name: portainer/agent:sts

# Copmposeupgrade variables
a1_compose_services: ['Pihole2', 'Ansible2']

# ZabbixAgent2 variables
zabbix_server: 192.168.64.115
zabbix_server_active: 192.168.64.115
zabbix_agent_hostname: 'VM.Docker.Backup'
